Lesson6
vytcus/eandrejevas pull request #8
Opened 2021-06-02 12:17 UTC by eimuc

+Homework - ![button](https://user-images.githubusercontent.com/43643903/120478556-a6cece00-c3b5-11eb-9df2-39521bd279d4.jpg)

2021-06-02 13:11 UTC, vytcus requested changes

2021-06-02 13:11 UTC, vytcus commented on src/index.css
> +.custom-number-input input:focus {
panašu, kad šios klasės nenaudojamos?

2021-06-02 19:14 UTC, eimuc commented on src/index.css
> +.custom-number-input input:focus {
.custom-number-input input:focus {
  outline: none !important;
} */
/* 
.custom-number-input button:focus {
  outline: none !important;
}

taip, šitos nenaudojamos, truputi kopijavau stilius nuo kelių vietų ir liko. tuoj sutvarkysiu

input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

o šita naudojama

2021-06-03 08:47 UTC, vytcus approved these changes

2021-06-03 11:02 UTC, merged